### ISSUE TITLE
Tables are not recognized

### ISSUE THREAD

**Issue by alison84r** [camelot-dev/camelot#102]
Hi,
I have one pdf , where I am not able to recognize the Tables. 
Is there any thing special settings I need to do. 
These are some types of tables I will be encountering. 

[drw0004.pdf](https://github.com/camelot-dev/camelot/files/3925627/drw0004.pdf)

**Comment by vinayak-mehta** [comment]
You can play with the `line_scale` option to help Camelot recognize these small tables.
