### ISSUE TITLE
Thank you & a PHP Wrapper

### ISSUE THREAD

**Issue by CImrie** [camelot-dev/camelot#105]
Hi,

Fantastic work on the library! I am starting a new project that relies heavily on extracting tables from PDF files. I wanted to use Amazon Textract because it was affordable but it doesn't provide any customisation like this. So thanks a lot, as it will be invaluable.

Since I predominantly work with Laravel & PHP I have wrapped the CLI with a PHP library.
Just a shout out if anyone ever needs to use Camelot in a PHP setting.

You can find it here: 
* [Packagist](https://packagist.org/packages/randomstate/camelot-php)
* [GitHub](https://github.com/randomstate/camelot-php)

Hope this helps!

**Comment by vinayak-mehta** [comment]
Thanks for creating a PHP wrapper! I've added it to the README.
