### ISSUE TITLE
Unable to recognized tables

### ISSUE THREAD

**Issue by gwh204** [camelot-dev/camelot#106]
Are there any settings I can use to auto detect these borderless tables? I've tried a number of different stream settings without success. 

Using Excalibur, I have manually identify the individual table regions and everything can be parsed perfectly. I'm looking to automate that detection process. Any help would be much appreciated!

[S1F1IND.pdf](https://github.com/camelot-dev/camelot/files/4021439/S1F1IND.pdf)

**Comment by vinayak-mehta** [comment]
Using Excalibur to select table regions would be the best strategy for this PDF

**Comment by abhilashabhardwaj** [comment]
Hello @gwh204, I'm also trying to automate the table_area parameters. Did you achieve this in your work? Or did you have to use some workaround?
Thanks in anticipation.
