### ISSUE TITLE
Unable to process landscape pdf files

### ISSUE THREAD

**Issue by lnicalo** [camelot-dev/camelot#107]
My issue is that camelot is unable to detect tables in landscape text pdf documents. I am getting a warning: UserWarning: page-1 is image-based, camelot only works on text-based pages. [lattice.py:393]

Pdf contains text and not a picture of the table. Is it possible to configure camelot to process landscape pdf docs?

Thanks.

**Comment by vinayak-mehta** [comment]
You can try rotating the PDF and then passing it into Camelot
