### ISSUE TITLE
getting coordinates of a page

### ISSUE THREAD

**Issue by achyuth588** [camelot-dev/camelot#113]
in table_areas field, the command is given as  
" >>> tables = camelot.read_pdf('table_areas.pdf', flavor='stream', table_areas=['316,499,566,337'])
>>> tables[0].df "

So here table_areas=['316,499,566,337']
how to know these co-ordinates of a pdf page.(x1,y1,x2,y2)

**Comment by laventy** [comment]
![image](https://user-images.githubusercontent.com/18434619/75301321-9ebce000-588e-11ea-8c44-c2ceaee82422.png)
