### ISSUE TITLE
Unable to retrieve table from document if there is more spacing in betwwen

### ISSUE THREAD

**Issue by KoustavCode** [camelot-dev/camelot#117]
I am unable to retrieve table which is appearing at the bottom of the page after some spacing.

Please any one can help attaching the sample page here.

[sample file1.pdf](https://github.com/camelot-dev/camelot/files/4281362/sample.file1.pdf)

**Comment by vinayak-mehta** [comment]
You can try specifying table areas and column separators https://camelot-py.readthedocs.io/en/master/user/advanced.html#specify-table-areas
