### ISSUE TITLE
Titles are extracted into the tables

### ISSUE THREAD

**Issue by lemonramen3** [camelot-dev/camelot#118]
https://stackoverflow.com/questions/60473093/how-to-extract-tables-from-pdfs-using-camelot-py-without-extracting-the-titles-o

**Comment by vinayak-mehta** [comment]
You can select the exact table area in this case https://camelot-py.readthedocs.io/en/master/user/advanced.html#specify-table-areas

**Comment by omer8690** [comment]
@vinayak-mehta 
What if I don't know the exact table area? 
I am having the same issue, titles above and below the table are extracted alongside the table itself. 
I tried changing the `layout_kwargs={"line_margin"}`, as well as other parameters but it doesn't seem to solve the issue.
Do you have any other suggestions?

**Comment by omer8690** [comment]
update on my last comment:
I found that it happened because pages in the pdf I was working with all have lines along the edges. When I selected a smaller part of the page (inside the 'edge lines') the table was extracted perfectly.
