### ISSUE TITLE
camelot.plotting.PlotMethods.filename unused?!?

### ISSUE THREAD

**Issue by jedie** [camelot-dev/camelot#120]
`PlotMethods.__call__()` takes the argument `filename` but it's unused, isn't it?

Seems this was made with: https://github.com/camelot-dev/camelot/commit/db3f8c689765bddf725f319e173c10402d5f312d#diff-364c2ff947aafef15111e866f5ad5614R13

**Comment by jedie** [comment]
https://github.com/camelot-dev/camelot/pull/121 will fix this.

**Comment by vinayak-mehta** [comment]
Thanks for reporting this! Added a review on the PR.
