### ISSUE TITLE
Camelot.read_pdf with flavor='lattice' does not detect a table with two rows

### ISSUE THREAD

**Issue by devspectre** [camelot-dev/camelot#124]
I have a landscape PDF and on a page it has three tables with correct and clear grid lines.
However, read_pdf detects only two tables and does not detect second table which has two rows and three columns.
Other tables have 6 rows.
Is there any option to specify minimum detectable row numbers?

**Comment by aoiy** [comment]
https://camelot-py.readthedocs.io/en/master/user/advanced.html#detect-short-lines
Change the line_scale parameter.

**Comment by devspectre** [comment]
Thank you, @aoiy !
It works. line_scale=50 made it to detect two-row tables.
