### ISSUE TITLE
Multiline text in a single cell is split into multiple cells

### ISSUE THREAD

**Issue by rohitgavval** [camelot-dev/camelot#143]
While using either the stream or the lattice flavor, text spanning multiple-lines in a single cell is extracted into multiple cells. Please refer to page 2 in [this pdf](https://github.com/camelot-dev/camelot/files/4605289/Presentation1.pdf). 

The cell showing text "Multi-line Header2" and "Multi-line V2" are extracted into multiple cells. I tried multiple values for the line_margin parameter from pdfminer by setting it to the layout_kwargs but couldn't resolve this issue. Any advice?

**Comment by khemon** [comment]
hello, 

I have the same issue, is there any way to solve this with current version ?

**Comment by bharj** [comment]
I would be interested in solution for this too.

**Comment by aflip** [comment]
Hello 

Using stream, and fiddling around with the row_tol amount, I was able to extract this fine

`table_trial = cm.read_pdf('Presentation1.pdf' , pages ='2', flavor = 'stream', row_tol=35)`

Gave me

![image](https://user-images.githubusercontent.com/59506464/90247673-b5fb8400-de54-11ea-9a6f-77760b53c0f9.png)

There's more info on teasing apart rows, and more in the docs here: https://camelot-py.readthedocs.io/en/master/user/advanced.html#improve-guessed-table-rows

**Comment by vinayak-mehta** [comment]
The table in your pdf looks similar to the table from [this part](https://camelot-py.readthedocs.io/en/master/user/advanced.html#process-background-lines) of the docs. You can try processing background lines as mentioned there and see if that works.
