### ISSUE TITLE
ValueError / ZeroDivisionError / empty dataframes while using read_pdf()

### ISSUE THREAD

**Issue by palask** [camelot-dev/camelot#157]
Hello,
I want to use Camelot to parse the tables on the second page of this pdf: [FEC-RO-DS-AM120iD-DE.pdf](https://github.com/camelot-dev/camelot/files/4842737/FEC-RO-DS-AM120iD-DE.pdf)

Even though similar pdfs work quite well, this one throws different exceptions, depending on which parameters I use with the read_pdf() function. Or if there are no additional parameters specified, except for the page number, the function just returns 4 empty dataframes.

Sample code:
```python
import camelot

file = "FEC-RO-DS-AM120iD-DE.pdf"

# Results in 4 dataframes, none of them has text in it
pdf = camelot.read_pdf(file, pages="2")

# Crash ("ValueError: min() arg is an empty sequence" in _text_bbox, stream.py:97
# _generate_columns_and_rows, stream.py:330
# extract_tables, stream.py:457
# parse, handlers.py:172
# read_pdf, io.py:117
# <module>, test.py:15)
region_0 = camelot.read_pdf(file, flavor="stream", table_areas=["400, 590, 820, 510"],
                            pages="2")

# Crash ("ZeroDivisionError: float division by zero in get_table_areas, core.py:221
# _nurminen_table_detection, stream.py:284
# _generate_table_bbox, stream.py:307
# extract_tables, stream.py:450
# parse, handlers.py:172
# read_pdf, io.py:117
# <module>, test.py:25)
region_1 = camelot.read_pdf(file, flavor="stream", table_regions=["440, 370, 800, 40"],
                            pages="2")

```

Version numbers:
```
Windows-10-10.0.19041-SP0
Python 3.7.7 (default, May  6 2020, 11:45:54) [MSC v.1916 64 bit (AMD64)]
NumPy 1.18.1
OpenCV 4.2.0
Camelot 0.8.0
```

**Comment by abhilashabhardwaj** [comment]
Hello Palask, how do you find the table areas?

**Comment by palask** [comment]
@abhilashabhardwaj I simply used the plot function provided by camelot and pyplot on a similar, working pdf to see the coordinates.

**Comment by palask** [comment]
Just as a quick note: I ran this code again yesterday (with updated packages), and the problems are gone. Maybe an update fixed it already?
Please feel free to close the issue, if there isn't anything left to check.
