### ISSUE TITLE
Using camelot in Google Cloud Functions

### ISSUE THREAD

**Issue by jethar** [camelot-dev/camelot#160]
The camelot package has a pre-requisite of **Tkinter and ghostscript**.

Is there a way to work around these pre-requisites for Google cloud funcions and/or AWS lambda, which do not allow explicit install of system packages.

A possible starting point could be - [Using Firebase Cloud Functions with Ghostscript for PDF to Image Conversion](https://tech.residebrokerage.com/using-firebase-cloud-functions-with-ghostscript-for-pdf-to-image-conversion-f81b248d3b22)

**Comment by EHadoux** [comment]
I don't know for GCF but for AWS Lambdas you can create a layer containing all your dependencies and set it as dependency of your function: https://docs.aws.amazon.com/lambda/latest/dg/configuration-layers.html

**Comment by vinayak-mehta** [comment]
You could create a docker image and deploy it using https://cloud.google.com/run
