### ISSUE TITLE
ImportError: cannot import name 'PDFTextExtractionNotAllowed' from 'pdfminer.pdfpage'.

### ISSUE THREAD

**Issue by Oleh-Hrebchuk** [camelot-dev/camelot#169]
>>> import camelot
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/camelot/__init__.py", line 6, in <module>
    from .io import read_pdf
  File "/usr/local/lib/python3.7/site-packages/camelot/io.py", line 5, in <module>
    from .handlers import PDFHandler
  File "/usr/local/lib/python3.7/site-packages/camelot/handlers.py", line 9, in <module>
    from .parsers import Stream, Lattice
  File "/usr/local/lib/python3.7/site-packages/camelot/parsers/__init__.py", line 3, in <module>
    from .stream import Stream
  File "/usr/local/lib/python3.7/site-packages/camelot/parsers/stream.py", line 10, in <module>
    from .base import BaseParser
  File "/usr/local/lib/python3.7/site-packages/camelot/parsers/base.py", line 5, in <module>
    from ..utils import get_page_layout, get_text_objects
  File "/usr/local/lib/python3.7/site-packages/camelot/utils.py", line 17, in <module>
    from pdfminer.pdfpage import PDFTextExtractionNotAllowed
ImportError: cannot import name 'PDFTextExtractionNotAllowed' from 'pdfminer.pdfpage' (/usr/local/lib/python3.7/site-packages/pdfminer/pdfpage.py)
>>> 

After build project I see this error.
Also, I see that package pdfminer.six-20200720 did release today.

**Comment by Oleh-Hrebchuk** [comment]
pip install pdfminer.six==20200517 if install older version all works fine

**Comment by vinayak-mehta** [comment]
I'll fix it right now and create a release.

**Comment by vinayak-mehta** [comment]
@xamey I saw your PR. I'll fix it here.

**Comment by carsonyl** [comment]
@vinayak-mehta pdfminer.six released version 20200726 today, which reverts PDFTextExtractionNotAllowedError back to PDFTextExtractionNotAllowed. I had to install pdfminer.six 20200720 to get it working again with camelot 0.8.1.

**Comment by vinayak-mehta** [comment]
Yes, I pointed out the breaking change on their gitter channel and a contributor reverted the change :sweat_smile: https://github.com/pdfminer/pdfminer.six/pull/461

I'm releasing camelot `0.8.2` with the revert.

**Comment by vinayak-mehta** [comment]
Maybe I should also yank `0.8.1` on PyPI.

**Comment by name-andy46** [comment]
Just installed this on conda, got the same error "cannot import PDFTextExtractionNotAllowed". I imported pdfminer.six and checked, it has PDFTextExtractionNotAllowedError. Realized that conda ditribution is till on 0.8.0.
So uninstalled from conda and installed with pip "camelot-py[cv]". This imports without error.

**Comment by aflip** [comment]
> @vinayak-mehta pdfminer.six released version 20200726 today, which reverts PDFTextExtractionNotAllowedError back to PDFTextExtractionNotAllowed. I had to install pdfminer.six 20200720 to get it working again with camelot 0.8.1.

This is what worked for me also.

**Comment by vinayak-mehta** [comment]
Please install the latest `v0.8.2` with `pip install --upgrade camelot-py`. This version for conda will be released soon. Right now, there's a blocker to do that: https://github.com/conda-forge/camelot-py-feedstock/pull/20

**Comment by aflip** [comment]
This works. confirmed.  Had to also update pdfminer via pip.

**Comment by aflip** [comment]
> Please install the latest `v0.8.2` with `pip install --upgrade camelot-py`. This version for conda will be released soon. Right now, there's a blocker to do that: [conda-forge/camelot-py-feedstock#20](https://github.com/conda-forge/camelot-py-feedstock/pull/20)

This worked. 

 Had to also run

'ip install --upgrade pdfminer`
