### ISSUE TITLE
ImportError: cannot import name 'PDFTextExtractionNotAllowedError' from 'pdfminer.pdfpage'

### ISSUE THREAD

**Issue by MartinThoma** [camelot-dev/camelot#176]
```python
import camelot

tables = camelot.read_pdf("PDF-export-example.pdf")
print(tables)
```

Versions:

* camelot-py==0.8.1 
* pdfminer==20191125         
* pdfminer.six==20181108 

I've uninstalled pdfminer now, but I get the same issue.

I've updated to `pdfminer.six==20200726 `, but still get the same issue.

**Comment by vinayak-mehta** [comment]
`camelot-py==0.8.2` should fix this. Can you please upgrade using `pip install --upgrade camelot-py`?

**Comment by MartinThoma** [comment]
Cool, now I don't get that mistake anymore. Thank you!
