### ISSUE TITLE
Why doesn't camelot find my table?

### ISSUE THREAD

**Issue by MartinThoma** [camelot-dev/camelot#177]
I'm using `camelot-py==0.8.2 ` and [this example PDF](https://github.com/MartinThoma/algorithms/blob/master/PDF/PDF-export-example.pdf) and this code:

```
import camelot

tables = camelot.read_pdf("PDF-export-example.pdf")
print(tables)
for table in tables:
    print(table)
```

It prints:

```
<TableList n=0> 
```

But there clearly is a table. The document was created with Microsoft Word.

What is the issue? Can I make it find that table?

**Comment by vinayak-mehta** [comment]
Camelot uses the lattice flavor by default, but that isn't a lattice table. More on lattice and stream: https://camelot-py.readthedocs.io/en/master/user/how-it-works.html

You can get that table by choosing the stream flavor and selecting a table area: https://camelot-py.readthedocs.io/en/master/user/advanced.html
