### ISSUE TITLE
How to get dimensions of pages with the tables?

### ISSUE THREAD

**Issue by nutsci** [camelot-dev/camelot#180]
Hello- is it possible to get the dimensions of the page that each table is on? I need to scale the extracted table areas to a rendered pdf of a different size. I can't find this in the documentation and hope I didn't miss it somewhere. Thanks!

**Comment by vinayak-mehta** [comment]
The library does not expose a pdf page layout directly, but you can use [this utils function / pdfminer snippet](https://github.com/camelot-dev/camelot/blob/master/camelot/utils.py#L796) to do that separately.
