### ISSUE TITLE
Answers for checkbox questions not being detected

### ISSUE THREAD

**Issue by aroc725** [camelot-dev/camelot#181]
Using: Windows 10, camelot version 0.8.2, Ghostscript version 9.52.

I saved a PDF file containing multiple tables, after having checked an answer for a couple of 'checkbox questions' in one of the tables. However, the answers aren't getting saved to the generated CVS/Excel files.

Is there a way to resolve this, or is saving answers to checkbox questions not something the current version of camelot is able to handle?

**Comment by aflip** [comment]
Could you upload the PDF or an example of what you're trying to do?

**Comment by aroc725** [comment]
> Could you upload the PDF or an example of what you're trying to do?

Sure, here's a link to the file:

https://www.dropbox.com/s/9typ30kn47vo0jh/COVID19%20Case%20Report%20Form%204.23.20.pdf?dl=0

**Comment by vinayak-mehta** [comment]
This is a form a not a table. You can try [using this setting](https://camelot-py.readthedocs.io/en/master/user/advanced.html#detect-short-lines) so that checkboxes are detected.

**Comment by aroc725** [comment]
Setting the 'line_scale' setting to 46 does display all the possible answers for two of the checkbox questions I looked at, but all the checkboxes are blank/empty. So I don't know which checkboxes were actually checked for those questions.
