### ISSUE TITLE
What OCR is used by camelot and does it always use OCR if pdf has text layer in it?

### ISSUE THREAD

**Issue by peeyushpashine** [camelot-dev/camelot#182]

**Comment by aflip** [comment]
Camelot does not use any OCR. It extracts text only.

**Comment by vinayak-mehta** [comment]
Camelot only works with text-based PDFs and not scanned documents. (As Tabula explains, "If you can click and drag to select text in your table in a PDF viewer, then your PDF is text-based".)

**Comment by vinayak-mehta** [comment]
The how it works section in the docs might be helpful for your question: https://camelot-py.readthedocs.io/en/master/user/how-it-works.html
