### ISSUE TITLE
Problem with column separators

### ISSUE THREAD

**Issue by nrygh** [camelot-dev/camelot#185]
I have a complex document, where sometimes a column has no or less separation with spaces.
Extraction with stream ist not consistent. 
Now i have tried to use the column separator and have specified the values, where to create a new column.
It works in generell, but sometimes it does not work and results are not consistent.
Could you please help?

**Comment by vinayak-mehta** [comment]
You can try changing the stream tolerances, please check the [advanced guide](https://camelot-py.readthedocs.io/en/master/user/advanced.html#improve-guessed-table-areas) to learn more.
