### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by arvindjj-git** [camelot-dev/camelot#190]
class conversion:
    tables = camelot.read_pdf('test_input.pdf')
    hold = tables
    print(hold)
    show = camelot.plot(tables[0],kind='text').show

if __name__ =='__main__':
    t = conversion()

output:
  if gives TableList n=0.

have included my source here. 
[test_input.pdf](https://github.com/camelot-dev/camelot/files/5127787/test_input.pdf)

**Comment by vinayak-mehta** [comment]
You need to use the stream flavor to parse this PDF.
