### ISSUE TITLE
Camelot does not find column lines when parsing table

### ISSUE THREAD

**Issue by pacedavis** [camelot-dev/camelot#194]
Please look at the attached file.  The 3rd table does find the correct number of columns when parsing the header of the table but all of the data seems to not be split up into columns.  Some of the text would not b/c it overlaps the column lines but the "line items" of the purchase order should be split up.  I have tried lattice and stream
[PO3.pdf](https://github.com/camelot-dev/camelot/files/5277885/PO3.pdf)

In some examples provided, much more complex tables are parsed correctly.  I must be doing something wrong.

**Comment by vinayak-mehta** [comment]
Hey! I will try to extract tables from this PDF when I get time from other issues. Meanwhile, can you try one of the advance settings with stream (this doesn't look like a lattice table)? https://camelot-py.readthedocs.io/en/master/user/advanced.html

**Comment by pacedavis** [comment]
Thank you for the response.  If I use the stream method, it picks up the data but all of it is one long string, not broken up into columns.

**Comment by vinayak-mehta** [comment]
Yes this looks like a difficult table for stream to parse. You might have to specify a table area or column x coordinates. Those parameters should help you get the data out.
