### ISSUE TITLE
Multiple line-breaks removed

### ISSUE THREAD

**Issue by leventebo** [camelot-dev/camelot#197]
I have multiline texts in cells of the table. Whenever there is an empty line in the middle of the text, I would expect to get multiple line-breaks, but only getting a single `\n`:
```
First line

Second line
```
I would expect `First line\n\nSecond line` but I'm getting `First line\nSecond line` with only one `\n` instead.
Can this somehow be configured?

The actual output is `S\nFirst line\necond line`, so the first letter of the text after a new line is always moved to the beginning of the cell, but I could move that back if I knew where the double line-breaks (empty lines) were in the original text.

**Comment by vinayak-mehta** [comment]
> I would expect First line\n\nSecond line but I'm getting First line\nSecond line with only one \n instead.
Can this somehow be configured?

No, text is placed on a PDF page using x,y coordinates, there is no information about newlines, and the library also doesn't account for large y differences between lines to emulate and add newline characters.

> The actual output is S\nFirst line\necond line, so the first letter of the text after a new line is always moved to the beginning of the cell, but I could move that back if I knew where the double line-breaks (empty lines) were in the original text.

Do you get `S\nFirst line\necond line` with a different setting? As it is different from `First line\nSecond line` mentioned in the line before that. It's difficult to suggest things when there is no PDF and sample code but maybe you could try using https://camelot-py.readthedocs.io/en/master/user/advanced.html#shift-text-in-spanning-cells

**Comment by kdannies** [comment]
I have the same problem. Picture is here:

![image](https://user-images.githubusercontent.com/1640073/198628141-52406eff-7d6e-4c1b-8a44-572c9104e8e8.png)

Code:

`tables = camelot.read_pdf(filename)`

Resulting text from this field:

     b\n  G\na)\nWindpark Dachsberg 3 GmbH &\nCo. KG\n)\nPotsdam\neschäftsanschrift:\nGregor-Mendel-Straße 24 A,\n14469 Potsdam


Is this fixable by any configuration? Help would be appreciated.
