### ISSUE TITLE
all cells are read as cid:xx

### ISSUE THREAD

**Issue by wbadry** [camelot-dev/camelot#199]
**Describe the bug**
When reading a table, all cells show **cid: xx** instead of the original text.

**Steps to reproduce the bug**
Steps used to install `Camelot`:
1. Followed [dependencies](https://camelot-py.readthedocs.io/en/master/user/install-deps.html)  and [pip](https://camelot-py.readthedocs.io/en/master/user/install.html) installation.

```python
import camelot

# Read PDF
tables = camelot.read_pdf('schools.pdf')

# print number of tables found
print(tables)

print('Second Table Dimension')
print(tables[1])

# Parsing report
tables[1].parsing_report

# Printing first few records of 2nd table
tables[1].df.head()
```
**Expected behavior**
Reading the second table.

**PDF**
[schools.pdf](https://github.com/camelot-dev/camelot/files/5402979/schools.pdf)

**Screenshots**
![2020-10-19_17-32-59](https://user-images.githubusercontent.com/5664750/96472826-3366ba80-1231-11eb-9a76-707b9ae8abc6.png)

**Environment**
 - OS: Windows 10 x64 version 2004
 - Python version: 
 - Numpy version:
 - OpenCV version: 3.7.8
 - Ghostscript version: 9.53.3
 - Camelot version: 0.8.2

**Comment by anakin87** [comment]
It is a known PDF problem.

In simple words, your PDF file doesn't contain characters mappings: it is possible to display the content but not to extract the text.

Please read [this](https://stackoverflow.com/questions/50773909/what-to-do-with-cids-in-text-extracted-by-pdfminer).

I don't think this is a bug of Camelot.

If you want to extract the text, you can use some OCR software, but you can't properly do table extraction with Camelot, beacause at the moment it doesn't support OCR.

**Comment by vinayak-mehta** [comment]
Thanks for pointing that out @anakin87! Also adding a `faq` label to this for a new FAQ page, I'll start working on that after next week. @anakin87 in case you want to start a PR with the FAQs that you've seen, I would love to add to that too!
