### ISSUE TITLE
Camelot parsed table_areas is not strictly parsed by my specified table areas and may slight beyond my table areas

### ISSUE THREAD

**Issue by realize-qzq** [camelot-dev/camelot#225]
Hi all, when using camelot to parse pdf table with the specified table areas, it **may extend slightly out of my table areas.** I want to avoid it. Here is my pdf, please see page 3.
[14-较低活化凝血时间下心房颤动消融术并发症的发生率及出血并发症的危险因素.pdf](https://github.com/atlanhq/camelot/files/6043220/14-.pdf).
You can see the title which is colored red by me and I don't want the title to be parsed in the result.
![image](https://user-images.githubusercontent.com/49114532/109161259-cbf9e200-77b1-11eb-9289-9b43c6b37589.png)

Here are my expected table areas ['309.12, 756.2, 538.56, 606.36'] and visualize the corresponding region with tools.
![image](https://user-images.githubusercontent.com/49114532/109160346-a1f3f000-77b0-11eb-8f65-b4aa437e89ed.png)
But camelot **still parse** the unneeded title which is **beyond my areas actually**. How can I **strictly** parse pdf with **specified table areas**? Thx!

![image](https://user-images.githubusercontent.com/49114532/109160961-73c2e000-77b1-11eb-87da-00a6da3c3907.png)

**Comment by Kumar-Tarun** [comment]
@realize-qzq You need to pass the computed table areas with the `table_areas` parameter instead of `table_regions`.

**Comment by realize-qzq** [comment]
> @realize-qzq You need to pass the computed table areas with the `table_areas` parameter instead of `table_regions`.

Thx, I typed the wrong parameter. By the way, sometimes this issue is caused by pdfminer which returns the wrong text position for camelot, see this issue https://github.com/pdfminer/pdfminer.six/issues/281
