### ISSUE TITLE
AttributeError from PDFMiner

### ISSUE THREAD

**Issue by vinayak-mehta** [camelot-dev/camelot#23]
@igormp
> Although I can't upload the bad PDF due to NDA reasons, this issue is well documented here, along with some solutions to it, and there's even a PR in place to fix that, but there seems to be no maintainer available to merge it.
>
> I'm not sure how this should be handled, since it's a PDFMiner problem, which seems to be unmaintained, and that reflects directly on camelot.

**Comment by vinayak-mehta** [comment]
- https://github.com/pdfminer/pdfminer.six/issues/210
- https://github.com/pdfminer/pdfminer.six/pull/228

**Comment by vinayak-mehta** [comment]
@igormp @dimitern How do you suggest we go about this? We can reach out to the maintainer on email, or start a fork.

**Comment by igormp** [comment]
The maintainers of both projects (the original PDFMiner and PDFMiner.six) still seem to be active, although not working on PDFMiner itself. 
The best course of action would be if we could somehow at least merge the PRs sent into the original project and then release a new version onto PyPi. Maybe we could reach the maintainers to add us as collaborators or pass the repo on to another active maintainer?

**Comment by vinayak-mehta** [comment]
https://github.com/pdfminer/pdfminer.six/issues/210#issuecomment-509800131

**Comment by fakabbir** [comment]
I saw great efforts in fixing pdfminer by Elad(@eladkehat) at https://github.com/eladkehat/yapdfminer. There are many improvements that he has collected from different PRs and fixes. Maybe we can involve him into the discussion in case we are thinking to contact the current maintainers to extend the maintainers list.

**Comment by eladkehat** [comment]
Thanks @fakabbir. I actually use Camelot and force my own version of PDFMiner due to the various open issues with the original. I'll be happy to help.

**Comment by igormp** [comment]
Now all that's left is to reach an actual maintainer on the original repo

**Comment by vinayak-mehta** [comment]
I see that @0xabu and @ganeshtata have merge access on the pdfminer.six repo, since they merged https://github.com/pdfminer/pdfminer.six/pull/230 and https://github.com/pdfminer/pdfminer.six/pull/227 fairly recently. I've pinged both of them on https://github.com/pdfminer/pdfminer.six/issues/210#issuecomment-509800681, let's wait for them to reply.

**Comment by vinayak-mehta** [comment]
@pietermarsman has suggested some changes on https://github.com/pdfminer/pdfminer.six/pull/228. @igormp @fakabbir Do you have bandwidth to look into it?

**Comment by fakabbir** [comment]
Yes, Sure I can do a PR this weekend then. Should I fork jtkese's repo https://github.com/pdfminer/pdfminer.six/pull/228 and do a PR on that, so that it gets added to the same conversation or a new PR. Which, you guys think will work faster/better ? 

The talks related to pdfminer.six happens here on https://gitter.im/pdfminer-six/Lobby

**Comment by vinayak-mehta** [comment]
You could fork jtkese's repo and add your commits to the same PR. If they take time to accept your commits, you could open a new PR with their and your commits.

**Comment by vinayak-mehta** [comment]
https://github.com/camelot-dev/camelot/issues/23#issuecomment-508947380
@igormp Looks like one upstream issue was fixed, are you still facing this problem?

**Comment by vinayak-mehta** [comment]
Please reopen if you still do.

**Comment by vinayak-mehta** [comment]
Awesome!
