### ISSUE TITLE
Can't correctly read stream-format table rows with misaligned values 

### ISSUE THREAD

**Issue by geistling** [camelot-dev/camelot#232]
**Describe the bug**
I'm having trouble reading in one specific page from [this menu](https://otbstoragestaging.blob.core.windows.net/media/Default/Menu/Nutrition/OTB%20Nutritional%20%26%20Allergen%20Matrix%204.1.16.pdf) with Camelot. Every other page has been fine, but this one is rendered as follows:
![image](https://user-images.githubusercontent.com/34081638/112872934-f67bdb00-908e-11eb-99df-4312b0bfbfd2.png)

As you can see, the first column has the following three columns' values preceding its own. 
![image](https://user-images.githubusercontent.com/34081638/112878034-786f0280-9095-11eb-93d6-899c09771be8.png)

I've tried fiddling with edge_tol, row_tol, column_tol, layout_kwargs (can confirm that [boxes_flow isn't working](https://github.com/camelot-dev/camelot/issues/223), btw), and split_text in different combinations to address this. Reducing row_tol to 0 gets me somewhere, but also puts the first column and the following columns in separate rows: 

![image](https://user-images.githubusercontent.com/34081638/112878459-fb905880-9095-11eb-89de-092321abef0c.png)

I believe this is the result of the row texts being slightly misaligned:
![image](https://user-images.githubusercontent.com/34081638/112878637-2d092400-9096-11eb-8ab7-b5a0422b8918.png)

I can't seem to address the issue, though.

**Comment by geistling** [comment]
Changing the line_overlap parameter in layout_kwargs solves this problem; I forked the repo and added the same changes that are in [this merge request](https://github.com/camelot-dev/camelot/pull/219) to make it possible to do so.

**Comment by vinayak-mehta** [comment]
👍🏽
