### ISSUE TITLE
Skipping image based pages

### ISSUE THREAD

**Issue by erkin98** [camelot-dev/camelot#235]
My pdf contains both text-based and image-based pages,is there any way to skip image based pages and parse text-based pages?

**Comment by geistling** [comment]
One way to do this would be to specify the numbers of the pages you want to process, like so: 

`camelot.read_pdf('your.pdf', pages='1, 3-5, 8')`

Have you tried this out yet?

**Comment by vinayak-mehta** [comment]
Another way could be to send `pages='all'` and then catch this warning `<filename> is image-based, camelot only works on text-based pages.` to skip image based pages.
