### ISSUE TITLE
Issue in copy_text = ['v'] is not working for tables split in multiple page.

### ISSUE THREAD

**Issue by ashwanidv100** [camelot-dev/camelot#238]
**Describe the bug**

copy_text = ['v'] is not working for a table split in multiple page.

**Steps to reproduce the bug**

table = camelot.read_pdf('pdf_name.pdf', , pages = '1-end', copy_text = ['v'] )
table.df

pdf tables should be splitted in 2 pages, where column 1 have only one entry throughout both the page.

**Expected behavior**

The value should be copied to all the rows that is splitted across multiple pages

**Code**
Add the Camelot code snippet that you used.
```
import camelot

table = camelot.read_pdf('pdf_name.pdf', , pages = '1-end', copy_text = ['v'] )
table.df

```

**PDF**

Wont' be able to share a pdf due to confidencial details but can share a screen shot. 

**Screenshots**
![image](https://user-images.githubusercontent.com/10371826/117099096-ee017900-ad8d-11eb-92f0-087443c457e6.png)

**Environment**
 - OS: Google Colab
 - Python version: 3.9
 - Numpy version: --
 - OpenCV version: --
 - Ghostscript version: --
 - Camelot version: 12.06.29

**Additional context**

**Comment by anakin87** [comment]
If the table is split over multiple pages, Camelot detects several different tables (one for each page).
So it seems natural to me that the "copy_text" parameter does not work as expected.

If I don't understand, please explain better this issue...

**Comment by ashwanidv100** [comment]
Yes, Thats correct. Is there any possible work around. 

Currently I'm considering pandas ffill() & bfill() based on the other columns continuity (solved only to some extent). But still that will not applies to other scenarios occuring to the other pages. 

Note: All the pages in pdf have headers with same name.

**Comment by ashwanidv100** [comment]
Update: I'm able to create a generic pythonic logic which will fill the data on other pages. For me, this issue is resolved. But keeping this issue open as it will be added advantage to have these approach incorporated in Camelot.

**Comment by vinayak-mehta** [comment]
@anakin87 is correct.

There's an open issue for this enhancement https://github.com/camelot-dev/camelot/issues/8

@ashwanidv100 Would love to know if you found any approaches that might generalize on different table headers (while accounting for length and string mismatches). We can continue the discussion on the original issue.
