### ISSUE TITLE
Report a Bug in 'table_regions'

### ISSUE THREAD

**Issue by Yichen0975** [camelot-dev/camelot#242]
**Describe the bug**
The parameters for 'table_regions' could not work when using Camelot read a PDF.

When use 'table_regions', I would only get a 'QUANTAL' result:
a. read the whole table and the whole PDF;
b. or reoprt 'ZeroDivisionError: float division by zero'.
(I'm sure I use the correct bbox rules)

**Steps to reproduce the bug**
Steps used to install `camelot`:

Add step here (you can add more steps too)
a. Read a PDF with complex tables by Camelot;
b. Set flavor = 'stream', and parameters for 'table_regions';
c. Print the table/tables (type: dataframe) with changing the parameters for 'table_regions'.
d. Got the result: read the whole PDF (even though the parameters just represent parts of the PDF) or read nothing.

**Expected behavior**
Read different parts when I change the parameters for for 'table_regions'.

**Code**
Add the Camelot code snippet that you used.
```
import camelot

# add your code here
```
table = camelot.read_pdf('PATH', flavor = 'stream', table_regions = ['x1,y1,x2,y2'])
print(table[0].df]

**PDF**
Add the PDF file that you want to extract tables from.
I could not do this since it's confidential.

**Screenshots**

**Environment**
 - OS: MacOS Big Sur 11.4
 - Python version: 3.9
 - Numpy version: 1.20.3
 - OpenCV version: 4.5.2.52
 - Ghostscript version: 0.7
 - Camelot version: 0.8.2

**Additional context**

**Comment by ckcr4lyf** [comment]
@Yichen0975 we had the same problem just start yesterday, can confirm it's related to latest version (`0.9.0`).

Going back to `0.8.2`, it works fine. Your bug report says you are on `0.8.2`, I suggest double check once. Especially if automated builds or similar, it may be trying to get the latest. Hope it helps

**Comment by Yichen0975** [comment]
> @Yichen0975 we had the same problem just start yesterday, can confirm it's related to latest version (`0.9.0`).
> 
> Going back to `0.8.2`, it works fine. Your bug report says you are on `0.8.2`, I suggest double check once. Especially if automated builds or similar, it may be trying to get the latest. Hope it helps



> **Describe the bug**
> The parameters for 'table_regions' could not work when using Camelot read a PDF.
> 
> When use 'table_regions', I would only get a 'QUANTAL' result:
> a. read the whole table and the whole PDF;
> b. or reoprt 'ZeroDivisionError: float division by zero'.
> (I'm sure I use the correct bbox rules)
> 
> **Steps to reproduce the bug**
> Steps used to install `camelot`:
> 
> Steps to reproduce the behavior:
> Add step here (you can add more steps too)
> a. Read a PDF with complex tables by Camelot;
> b. Set flavor = 'stream', and parameters for 'table_regions';
> c. Print the table/tables (type: dataframe) with changing the parameters for 'table_regions'.
> d. Got the result: read the whole PDF (even though the parameters just represent parts of the PDF) or read nothing.
> 
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> Read different parts when I change the parameters for for 'table_regions'.
> 
> **Code**
> Add the Camelot code snippet that you used.
> 
> ```
> import camelot
> 
> # add your code here
> ```
> 
> table = camelot.read_pdf('PATH', flavor = 'stream', table_regions = ['x1,y1,x2,y2'])
> print(table[0].df]
> 
> **PDF**
> Add the PDF file that you want to extract tables from.
> I could not do this since it's confidential.
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> **Environment**
> 
> * OS: MacOS Big Sur 11.4
> * Python version: 3.9
> * Numpy version: 1.20.3
> * OpenCV version: 4.5.2.52
> * Ghostscript version: 0.7
> * Camelot version: 0.8.2
> 
> **Additional context**
> Add any other context about the problem here.

Hello, 

thanks for your reply and thanks for your suggestions, I’d like to try today.

Best regards,
Yichen

**Comment by Yichen0975** [comment]
> @Yichen0975 we had the same problem just start yesterday, can confirm it's related to latest version (`0.9.0`).
> 
> Going back to `0.8.2`, it works fine. Your bug report says you are on `0.8.2`, I suggest double check once. Especially if automated builds or similar, it may be trying to get the latest. Hope it helps

Dear ckcr4lyf:

Thanks for your reply and thanks for your suggestions. However, after double check the version of Camelot in my computer that I am sure I use the 0.8.2 and the problem remains.

Best regards,
Yichen

**Comment by awa5114** [comment]
I also have this issue. Why does this occur?

**Comment by Yichen0975** [comment]
> I also have this issue. Why does this occur?

I don't know, I think perhaps it's a bug and therefore I report it here.
And at present I try to use other tools to extract tables from PDF (sad....

**Comment by awa5114** [comment]
@Yichen0975 it looks like this project has been discontinued. The last commit was made about 2 years ago....

**Comment by vinayak-mehta** [comment]
Hey everyone, the input strings that are passed in should be `x1,y1,x2,y2` where `(x1, y1)` -> top-left and `(x2, y2)` -> bottom-right. You can find more info in the section here: https://camelot-py.readthedocs.io/en/master/user/advanced.html#specify-table-areas This part of the codebase hasn't changed from 0.8.2 to 0.9.0 so that shouldn't be the issue.

**Comment by vinayak-mehta** [comment]
You can also check out usage in the test here: https://github.com/camelot-dev/camelot/blob/master/tests/test_common.py#L69
