### ISSUE TITLE
Support Reading directly from BytesIO

### ISSUE THREAD

**Issue by omarsumadi** [camelot-dev/camelot#245]
Looking to use Camelot instead of Tabula; however, Tabula supports reading directly from a 'Bytes-like' object such as BytesIO or a Bytearray, whereas Camelot does not.

Is this something in the roadmap? Should be an extension of the URL acceptance PR done awhile ago.
Right now, the current solution is to: convert the files into PDFs, doubling the time it takes versus Camelot.

Thanks,
Omar

**Comment by vinayak-mehta** [comment]
@omarsumadi This would awesome to have but I might not have enough bandwidth to do this in the near term. Would you like to work on this and submit a PR?
