### ISSUE TITLE
table_areas and table_regions not working on lattice flavour

### ISSUE THREAD

**Issue by MagicAP-QA** [camelot-dev/camelot#247]
This pdf i am unable to extract, it is bordered. Even after passing table_areas and table_regions its not working
[1610.00024v1.5.pdf](https://github.com/camelot-dev/camelot/files/6770809/1610.00024v1.5.pdf)

**Comment by anakin87** [comment]
Please report a detailed example.

**Comment by ZafarShadman09** [comment]
**Earlier Configuration Used :** 
stream: lattice
flag_size: True

Table was not getting extracted
So i passed the table coordinates in conf **table_areas** and **table_regions**, still no table was found.
This was original issue.

**New Configuration**
stream: lattice
flag_size: True
line_scale:50
I am able to detect and extract the table. But i see spanning is not covered.
In the image **Power and Cooling**  should span over column B and C, but its coming under B.

![image](https://user-images.githubusercontent.com/55151084/125059440-f4330f00-e0c8-11eb-92f1-176d5605ac45.png)

**Comment by vinayak-mehta** [comment]
Original issue can be solved by using line_scale to detect short lines: https://camelot-py.readthedocs.io/en/master/user/advanced.html#detect-short-lines

Writing spanning cells in Excel files is not supported yet.

**Comment by ZafarShadman09** [comment]
Since HTML's support spanning cells, so I tried to export to HTML but its not handling.
Any suggestions...
![image](https://user-images.githubusercontent.com/55151084/125236744-1a8fbf00-e302-11eb-882e-e5889f46764b.png)

**Comment by jimhall** [comment]
You could pass the resulting table from Camelot into [XlsxWriter](https://xlsxwriter.readthedocs.io/index.html) the [merge_range()](https://xlsxwriter.readthedocs.io/worksheet.html#merge_range) function. It has really great documentation on how to use it.

**Comment by vinayak-mehta** [comment]
@jimhall That's a great suggestion!

@ZafarShadman09 Sorry if I wasn't clear earlier. Excel and HTML support writing tables with spanning cells in their format, but Camelot doesn't support _writing cells in the spanning format_ yet.

**Comment by ZafarShadman09** [comment]
Thanks @vinayak-mehta @jimhall
