### ISSUE TITLE
Column spanning is not handled in stream flavor 

### ISSUE THREAD

**Issue by ZafarShadman09** [camelot-dev/camelot#248]
Every thing read properly except for the column header.
[0902.1884v1.1.pdf](https://github.com/camelot-dev/camelot/files/6771582/0902.1884v1.1.pdf)

![image](https://user-images.githubusercontent.com/55151084/124639188-7fce5500-dea9-11eb-890b-444b620227b5.png)

**Comment by ZafarShadman09** [comment]
B and C column should spanned together and D and E should be spanned together.

**Comment by vinayak-mehta** [comment]
Hi @ZafarShadman09, right now camelot doesn't support writing spanning cells in Excel files, but it would be a useful enhancement. Would you like to work on it and submit a PR?

**Comment by ZafarShadman09** [comment]
@vinayak-mehta I would definitely love to contribute on this.
