### ISSUE TITLE
Camelot unable to parse table that contains inconsistent number of columns

### ISSUE THREAD

**Issue by brsolomon-deloitte** [camelot-dev/camelot#264]
**Describe the bug**

Camelot unable to parse table that contains inconsistent number of columns. I've looked through the [advanced usage docs](https://camelot-py.readthedocs.io/en/master/user/advanced.html) but am not seeing a solution.

**Steps to reproduce the bug**

```
>>> import camelot
>>> tables = camelot.read_pdf(filepath='CNSSI_No1253.pdf', pages='48')

>>> tables[0].data[0]
['ID', 'TITLE', 'Confidentiality', 'Integrity', 'Availability']
>>> tables[0].data[1]
['', '', 'L \nM \nH', 'L \nM \nH', 'L \nM \nH']
>>> tables[0].data[2]
['SI-16', 'Memory Protection', '', 'X \nX', '']
```

**Expected behavior**

Rows of `data` above should have 9 rather than three values for each value in the red/white/blue matrix, e.g.

```
>>> tables[0].data[2]
['SI-16', 'Memory Protection', '', '', '', '', 'X', 'X', '', '', '']
```

**PDF**

https://www.dcsa.mil/portals/91/documents/ctp/nao/CNSSI_No1253.pdf

**Screenshots**

![Screen Shot 2021-08-30 at 5 17 23 PM](https://user-images.githubusercontent.com/81818815/131406838-6e44712d-e3c0-4a2c-b063-50f435f95524.png)

**Environment**

- OS: MacOS
- Python version: 3.9.6
- Numpy version: 1.21.1
- OpenCV-python version: 4.5.3.56
- Camelot version: 0.10.1

**Comment by tiagosamaha** [comment]
This can occur due background color. Try to increase "line_scale" to detect the lines.

`tables = camelot.read_pdf(filepath='CNSSI_No1253.pdf', pages='48', line_scale=30)`
