### ISSUE TITLE
How gsdll on Windows?

### ISSUE THREAD

**Issue by andkirby** [camelot-dev/camelot#265]
Hi team, 

Really need help here. 
https://stackoverflow.com/questions/69064465/how-to-feed-ghostscript-dll-library-to-python-in-windows
I have installed the ghostscript app for windows, but Python still does not "see" it.
Details by the link.

Thanks in advance

**Comment by tiagosamaha** [comment]
Did you add ghostscript to environment variables?

**Comment by alwinw** [comment]
Appears the original poster has marked their SO question as solved: https://stackoverflow.com/a/69065163

For anyone else that comes across this, here is a link to the official docs: https://camelot-py.readthedocs.io/en/master/user/install-deps.html

@tiagosamaha you can probably close this issue 🙂

**Comment by tiagosamaha** [comment]
@vinayak-mehta Could you close this issue?

**Comment by tiagosamaha** [comment]
@andkirby Was solved?

**Comment by andkirby** [comment]
@tiagosamaha Yes, I wrote the answer in by the link. It was about PATH and IDE reload (the last one I didn't expect it must be done).
Thank you for your involvement, guys!
