### ISSUE TITLE
parsing PDF with rows in different sizes

### ISSUE THREAD

**Issue by alissonsv** [camelot-dev/camelot#271]
Hello, I'm trying to parse this PDF been a while, and tried almost all configs, even been read the code to find a solution.
![pdf](https://user-images.githubusercontent.com/7702689/136618532-d13afc61-5794-45ac-be35-c614d78507fc.png)

as you can see, the date at first column is not at the top of the cell, so the table get parsed like this:
_the `...` are the cells that I had to censor_

|      |        0           |      1 |          2           |       3           |        4          |
|---- |----------------- | ------ | ----------------- | --------------- | --------------- |
| 0   |   30/07/2021|     ... |     052309      |  180,00       | 258.929,59 |
| 1   |                     |     ... |                       |                    |                    |
| 2   |                     |     ... |                       |                    |                    |
| 3   | 30/07/2021  |     ... |     041165      |  455,89       | 259.385,48 |
| 4   |                     |     ... |                       |                    |                    |
| 5   |                     |     ... |                       |                    |                    |
| 6   | 30/07/2021  |     ... |     052440      |  180,00       | 259.565,48 |
| 7   |                     |     ... |                       |                    |                    |
| 8   |                     |     ... |                       |                    |                    |
| 9   | 30/07/2021  |     ... |     052234      |  180,00       | 259.745,48 |
| 10 |                     |     ... |                       |                    |                    |
| 11 |                     |     ... |                       |                    |                    |
| 12 | 30/07/2021  |     ... |     863314      |  202,17       | 259.947,65 |
| 13 |                     |     ... |                       |                    |                    |
| 14 |                     |     ... |                       |                    |                    |
| 15 | 30/07/2021  |     ... |     875321      |    15,00       | 259.962,65 |
| 16 |                     |     ... |                       |                    |                    |
| 17 |                     |     ... |                       |                    |                    |
| 18 | 30/07/2021  |         | 224723423    |  576,25       | 260.538,90 |
| 19 |                     |     ... |                       |                    |                    |
| 20 |                     |     ... |                       |                    |                    |
| 21 | 30/07/2021  |     ... |     873665      |    30,00       | 260.568,90 |
| 22 |                     |     ... |                       |                    |                    |
| 23 |                     |     ... |                       |                    |                    |
| 24 | 30/07/2021  |     ... |       SI01053   | -15.000,00 | 245.568,90 |
| 25 |                     |     ... |                       |                    |                    |
| 26 | 30/07/2021  |     ... |                       | -309,79       | 245.259,11 |
| 27 | 30/07/2021  |     ... |                       | -3.120,10    | 242.139,01 |
| 28 | 30/07/2021  |     ... |                       | -141,48       | 241.997,53 |
| 29 | 30/07/2021  |     ... |                       | -3.089,90    | 238.907,63 |
| 30 | 30/07/2021  |     ... |                       | -1.150,99    | 237.756,64 |
| 31 | 30/07/2021  |     ... |                       | -383,08       | 237.373,56 |
| 32 | 30/07/2021  |     ... |                       | -9.456,24    | 227.917,32 |
| 33 | 30/07/2021  |     ... |                       | -570,00       | 227.347,32 |
| 34 | 30/07/2021  |     ... |                       | -820,00       | 226.527,32 |
| 35 | 30/07/2021  |     ... |                       | -1.487,99    | 225.039,33 |
| 36 | 30/07/2021  |     ... |                       | -1.021,67    | 224.017,66 |
| 37 | 30/07/2021  |     ... |                       | -965,00       | 223.052,66 |
| 38 | 30/07/2021  |     ... |                       | -871,12       | 222.181,54 |
| 39 | 30/07/2021  |     ... |                       | -2.441,50    | 219.740,04 |
| 40 |                     |     ... |                       |                    |                    |
| 41 | 30/07/2021  |         | SEFAZMT-C  |     -933,10   | 218.806,94 |
| 42 |                     |     ... |                       |                    |                    |
| 43 |                     |     ... |                       |                    |                    |
| 44 | 30/07/2021  |         | DARF81COO | -15.037,94 | 203.769,00 |
| 45 |                     |     ... |                       |                    |                   |
| 46 |                     |     ... |                       |                    |                   |
| 47 |                     |     ... |                       |                    |                   |
| 48 | 30/07/2021  |         |     SI01268     | -3.946,03   | 199.822,97 |
| 49 |                     |     ... |                       |                   |                     |
| 50 |                     |     ... |                       |                   |                     |
| 51 |                     |     ... |                       |                   |                     |
| 52 |                     |     ... |                       |                   |                     |
| 53 | 30/07/2021  |         |       I01299     | -1.877,45   | 197.945,52  |
| 54 |                     |     ... |                       |                   |                     |
| 55 |                     |     ... |                       |                   |                     |
| 56 |                     |     ... |                       |                   |                     |
| 57 | 30/07/2021  |     ... |     I01307       | -2.636,85   | 195.308,67  |
| 58 |                     |     ... |                       |                   |                     |
| 59 |                     |     ... |                       |                   |                     |
| 60 | 30/07/2021  |         |DARF81COO  |   -8.485,45 | 186.823,22 |
| 61 |                     |     ... |                       |                    |                    |
| 62 |                     |     ... |                       |                   |                     |
| 63 |                     |     ... |                       |                   |                     |
| 64 | 30/07/2021  |         |  CX198172    |    50,00      |186.873,22   |
| 65 |                     |     ... |                       |                   |                     |
| 66 |                     |     ... |                       |                   |                     |
| 67 |                     |     ... |                       |                   |                     |

sorry for the long table, that was the way I found to it be clear

so, is there a way to parse the second column all together in a row with the others? 
*the row_tol doesn't work as the rows have different sizes across the pages*

It'll be great if there's a way to join them in row by it's colors, as the rows are in a striped style.

Thanks in advance!

**Comment by alissonsv** [comment]
Hey there!
Posting here what was the configs that worked for parsing this table:
```js
tables = camelot.read_pdf(
        filepath,
        flavor='stream',
        row_tol=14,
        edge_tol=50,
        pages='all',
        column_tol=-4
    )
```

**Comment by lahpoplarhomes** [comment]
Sorry newbie to github, but how can I view the solution on this after this issue was closed? Thanks in advance

**Comment by alissonsv** [comment]
hi @lahpoplarhomes, for my issue the solution is just above your comment, at https://github.com/camelot-dev/camelot/issues/271#issuecomment-963111544

**Comment by lahpoplarhomes** [comment]
> hi @lahpoplarhomes, for my issue the solution is just above your comment, at https://github.com/camelot-dev/camelot/issues/271#issuecomment-963111544

Thank youuu
