### ISSUE TITLE
Does camelot only work for a one-page pdf?

### ISSUE THREAD

**Issue by shiyueee19** [camelot-dev/camelot#277]
I tried to read a pdf with a large table across many pages, but only the two tables on the first page were read:

`tables
TableList n=2
tables[0]
Table shape=(5, 4)
tables[1]
Table shape=(19, 11)`

Does camelot only work for a one-page pdf? How can I extract all tables in the pdf file?

**Comment by cosxsinxds** [comment]
same problem
