### ISSUE TITLE
Optimize memory usage for long PDFs

### ISSUE THREAD

**Issue by anakin87** [camelot-dev/camelot#28]
Using Camelot for some very long PDFs (>500 pages), I noticed that memory usage can grow significantly (in my experience, it can reach 30 GB and more).

I don't know if I'm doing something wrong.

Anyway, I found this solution: to divide the extraction into some chunks (for example, chunks of 50 pages); at the end of every chunk extraction, data are saved to disk.
Doing so, I succeed in limiting memory usage to a maximum of 4 GB, even for PDF of about 3000 pages.

@vinayak-mehta : what do you think about this approach? It could be useful? Are there better ways to limit memory usage?

(obviously, if the data saved on disk, later are all loaded into memory, the problem persists)

**Comment by vinayak-mehta** [comment]
Woah 30 GB is a lot. I haven't had tried extracting tables from such large PDFs (~3000 pages). Is the memory is being taken up by pandas dataframes? Chunked extraction looks like a good way to go. What does your code snippet look like?

Also, if you don't mind me asking, what do these 3000 page PDFs contain? :sweat_smile:

**Comment by anakin87** [comment]
Yes, memory is being taken up by pandas dataframes.
These long PDF contain regional balance sheets.

My code (chunked extraction) is similar to this:

from __main__ import logger
import camelot
import shutil
import pathlib
import json
import os
import glob


def chunks(l, n):
    """Yield successive n-sized chunks from l."""
    for i in range(0, len(l), n):
        yield l[i:i + n]




def extract_tables_from_path(filename,pages,params=None):


    std_params_set = {
        'flavor': 'lattice',
        'line_scale': 65,
        'copy_text': ['h', 'v'],
        'split_text': True
    }

    # keys to export in JSON
    selected_keys = ['rows',
                     'whitespace',
                     '_bbox',
                     'cols',
                     'page',
                     'shape',
                     'flavor',
                     'order',
                     'accuracy']

    logger.info('\n\n' + '*' * 50 + 'START' + '*' * 50)
    logger.info('WORKING ON FILE {}'.format(filename))


    dir_name = filename.rpartition('/')[-1].rpartition('.')[0]
    dir_path = '/comuni-data/exp_tables/' + dir_name
    dir_temp=dir_path+'/temp'

    # Clean and recreate output directory
    try:
        shutil.rmtree(dir_path, ignore_errors=True)
        pathlib.Path(dir_temp).mkdir(parents=True, exist_ok=True)
    except:
        logger.exception('Error in cleaning/creating output directory')
        return None  

    params_set = params if params else std_params_set

    logger.info('USING THE FOLLOWING PARAMETERS: {}'.format(params_set))        


    # Control page number (by Camelot method)
    # and subdivide the extraction work into 50-pages parts.
    # AT THE END OF EVERY PART, SAVE THE DATA ON DISk AND FREE RAM
    
    handler=camelot.handlers.PDFHandler(filename)
    pages_list=handler._get_pages(filename,pages=pages)

    pages_chunks=list(chunks(pages_list,50))

    last_index=0
    tot_tables=0
    index=0



    for chunk in pages_chunks:
        tables=[]
        new_table_list=[]

        pages_string=str(chunk).replace('[','').replace(']','')



        try:
            tables = camelot.read_pdf(filename, pages=pages_string, **params_set)
        except Exception as e:
            logger.exception('ERROR IN TABLE EXTRACTION')
            return None




        # First filter      
        new_table_list =[table for table in tables if table.shape != (1, 1)]

        # Second filter

        new_table_list = [table for table in new_table_list if (table.parsing_report['accuracy'] > 75 \
                          or table.parsing_report['accuracy'] < 0) \
                          and table.parsing_report['whitespace'] < 80\
                          and '(cid:' not in str(table.data)]

   

        logger.info('SAVING EXTRACTION')

        # Exports in JSON the selected fields
        tables_bboxes = []

        for index, table in enumerate(new_table_list,last_index):
            table_dict = {key: table.__dict__[key] for key in selected_keys}

            table_dict['id'] = index
            table_dict['filepath'] = filename
            table_dict['json_data'] = table.__dict__['df'].to_json()

            table_filename = '{}/table-{}.json'.format(dir_path, index)


            with open(table_filename, "w") as file:
                json.dump(table_dict, file)

            
        last_index=index
        tot_tables+=len(new_table_list)


        

    logger.info('{} VALID TABLES DETECTED'.format(tot_tables))
    logger.info('*' * 50 + 'END' + '*' * 50)        

    api_response=ApiResponse(n_of_valid_tables=tot_tables,output_directory=str(pathlib.Path(dir_path).resolve()))

    
    return api_response


I hope it can be useful.
Thank you for Camelot!

**Comment by vinayak-mehta** [comment]
I think this should instead be part of the FAQ / guidelines i.e. one should flush tables to disk every `n` pages.

**Comment by dhdaines** [comment]
Hi, the actual reason this is happening is because the lattice parser is holding onto the image data for the entire page for each table.  This can get extremely large when there are a lot of pages or a lot of tables (or both!) since the image data is uncompressed.

Since the image data is only used for plotting/visual debugging, it would be nice to have an option to `camelot.read_pdf` to not do this in the case where you don't want to do any plotting.

In fact I'm not sure it's really a great idea to save it in the parser at all, because if it doesn't exist it will get recreated anyway if you call `camelot.plotting.draw_pdf`.  The extra cost of rendering the page twice is probably quite acceptable here.  I'm going to open a new issue and link to this one...
