### ISSUE TITLE
This PDF doesnt work  #colab

### ISSUE THREAD

**Issue by raven44099** [camelot-dev/camelot#291]
**Describe the bug**

````
tables = camelot.read_pdf('/content/drive/MyDrive/colab_repo/waste/acssynbio.1c00353.pdf', pages = '1-7', process_background=True)
````
returns 4 tables that are  unusable.
see: https://colab.research.google.com/drive/12RxZNH68ueb46suWOxZf_m_ixj_3jb2m?usp=sharing

**Expected behavior**

find the table

**PDF**

https://pubs.acs.org/doi/10.1021/acssynbio.1c00353

<details><summary>Screenshot</summary>
<p>

![image](https://user-images.githubusercontent.com/67215370/158523226-fafc8c29-de56-419f-9c01-8219cb4715d4.png)

</p>
</details>

**Environment**

google colab, default

**Comment by ramSeraph** [comment]
You might have better luck with `parser="stream"` argument and without the `process_background=True` argument

**Comment by raven44099** [comment]
Indeed.
It gives me now 8 tables and the fifth corresponds to table paper.t2.
Table paper.t1 and paper.t3 are not found but I am interested in paper.t2. Thank you.
