### ISSUE TITLE
Can't use 'columns' parameter even with stream

### ISSUE THREAD

**Issue by Artyrm** [camelot-dev/camelot#303]
**Describe the bug**
If using columns parameter even with flavor 'stream' it still rises error:
`ValueError: columns cannot be used with flavor='lattice'`

**Steps to reproduce the bug**
`tables = camelot.read_pdf(file_name, flavour="stream", columns = temp, joint_tol = 12, pages = str(first_page) + "-" + str(last_page))`

**Environment**

- OS: Ubuntu
- Python version: 3.7.13
- Numpy version: 1.21.6
- OpenCV version: 4.1.2
- Ghostscript version: 9.26
- Camelot version: 0.10.1

**Comment by LaKenLin** [comment]
Hi Artyrm,

Be aware that you spelled flavo**u**r instead of flavor. I am currently using camelot version 0.10.1 with flavor='stream' and columns given without issues. Therefore, I suspect, that your issue comes from the misspelling.

Cheers!

**Comment by Artyrm** [comment]
Hi @LaKenLin.

Ouch, that was unexpected, didn't think that error should be about columns, when an unknown parameter is used before them.

Well, thanks, I guess we should close this now :)
