### ISSUE TITLE
access violation writing 0x076ED670

### ISSUE THREAD

**Issue by KOLANICH** [camelot-dev/camelot#31]
rc = libgs.gsapi_init_with_args(instance, len(argv), c_argv)
OSError: exception: access violation writing 0x076ED670

32-bit python
latest ghostscript

**Comment by null-directory** [comment]
Did you have a solution to this? I am seeing the same error.

**Comment by KOLANICH** [comment]
The error was resolved by my PR. Install from this repo, not from pypi.

**Comment by manigandan-dorairaj** [comment]
Thanks, it worked. How to promote this to pypi?

**Comment by vinayak-mehta** [comment]
> Thanks, it worked. How to promote this to pypi?

I'll make a release soon.

**Comment by m1433** [comment]
> The error was resolved by my PR. Install from this repo, not from pypi.

please explain more
i'm new to python
