### ISSUE TITLE
It seems tables with only one line are not identified as such?

### ISSUE THREAD

**Issue by pboettch** [camelot-dev/camelot#327]
I have some PDF (generated from Word's docx I think) where sometimes one line of the table is on a second page. In this case camelot does not identify the (second) table.

I tried several things, I transformed the pages to black and white with `gs`. I merged the pages with `dfjam --nup 1x2 --paper a4paper <filename>` before passing them to camelot. Still, camelot does not extract the second table.

I tried Camelot 0.10.1 installed via pip and the master-branch from here.

This is the original file with two pages:

[Vinzieux 2022.pdf](https://github.com/camelot-dev/camelot/files/9558377/Vinzieux.2022.pdf)

after converting it I have everything on one page

[Vinzieux 2022-pdfjam.pdf](https://github.com/camelot-dev/camelot/files/9558385/Vinzieux.2022-pdfjam.pdf)

```
>>> iimport camelot
>>> camelot.read_pdf("Vinzieux 2022-pdfjam.pdf")
<TableList n=1>
```

**Environment**

- OS: Linux
- Python version: Python 3.10
- Numpy version: 1.21.5
- OpenCV version: 4.6.0
- Ghostscript version: 0.7
- Camelot version: 0.10.1 or master

**Comment by ramSeraph** [comment]
When on separate pages experiment with https://camelot-py.readthedocs.io/en/master/user/advanced.html#detect-short-lines it might work.. on single pages.. I am not so sure

**Comment by pboettch** [comment]
I switched to pdfplumber which, for my case, does exactly what I needed.
