### ISSUE TITLE
Is this no longer maintained?

### ISSUE THREAD

**Issue by NixBiks** [camelot-dev/camelot#330]
I just want to ask if this is no longer maintained? Wonder if anybody "took over" somewhere?

**Comment by ramSeraph** [comment]
If someone hasn't "taken over" yet.. Let's discuss if anyone is willing to.. here?

**Comment by nikhilvishwanath** [comment]
I'd like to contribute

**Comment by Pravin770** [comment]
Im in

**Comment by ramSeraph** [comment]
Let's just put an arbitrary quorum of 5 before we start moving forward with this?. Given prior history, I would say that would help with some redundancy.. if some people walk away. Alternatively, We can just start a repository and pick a name and start, If anyone starts I will pitch in.

**Comment by ramSeraph** [comment]
First order of business would be to clear the most obvious PRs that should have gone in by now.

**Comment by NixBiks** [comment]
I've recently chatted with the author @vinayak-mehta - he is planning to return soon is the last I've heard.

**Comment by NikilXYZ** [comment]
bump

**Comment by vinayak-mehta** [comment]
Hey folks, closing this one. We can use https://github.com/camelot-dev/camelot/issues/343 instead.
