### ISSUE TITLE
Zero division error

### ISSUE THREAD

**Issue by chenchunaidu** [camelot-dev/camelot#335]
**Describe the bug**

```
text_in_bbox
    if (bbox_intersection_area(ba, bb) / bbox_area(ba)) > 0.8:
ZeroDivisionError: float division by zero
```

**Steps to reproduce the bug**

**Expected behavior**

**Code**

```
import camelot
tables2=camelot.read_pdf('file.pdf', flavor='stream', pages='all')
print(tables2)

# add your code here
```

**PDF**

**Screenshots**

**Environment**

- OS: [e.g. macOS]
- Python version:
- Numpy version:
- OpenCV version:
- Ghostscript version:
- Camelot version:

**Additional context**

**Comment by bosd** [comment]
Thanks for mentioning this issue. This has been fixed, checkout out the latest release.
