### ISSUE TITLE
Zero Division Error : float division by zero

### ISSUE THREAD

**Issue by Pravin770** [camelot-dev/camelot#336]
Tried to extract the table from pdf by using Camelot . But it was throwing Zero Division Error. Attached the code and the table below

Table
![image](https://user-images.githubusercontent.com/56891610/201694542-deb600cc-2531-4634-8764-6523be710fbd.png)

**Code**

```
import camelot

tables2=camelot.read_pdf('file1.pdf', pages='19', flavor = 'stream')
tables2

```

![image](https://user-images.githubusercontent.com/56891610/201694432-48fd4bc0-df42-45e8-bb50-a1427e32eef1.png)

**Comment by djay** [comment]
I'm getting zerodivisionerror with this file also - https://ddc.moph.go.th/uploads/ckeditor2//files/report%20weekly%202023-01-20.pdf

**Comment by bosd** [comment]
Thanks for mentioning this issue. This has been fixed, checkout out the latest release.
