### ISSUE TITLE
PdfFileReader is deprecated and was removed in PyPDF2 3.0.0

### ISSUE THREAD

**Issue by szeswee** [camelot-dev/camelot#339]
**Describe the bug**

Version 3.0.0 of `PyPDF2` was just released today (23 Dec 2022), which includes a breaking change for removing `PdfFileReader` (see [changelog](https://pypdf2.readthedocs.io/en/stable/meta/CHANGELOG.html#version-3-0-0-2022-12-22)). As a result, all new installs and usage of `camelot-py` will raise the following exception:

```
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    camelot.read_pdf(PDF_FILE_PATH)
  File ".venv/py37/lib/python3.7/site-packages/camelot/io.py", line 117, in read_pdf
    **kwargs
  File ".venv/py37/lib/python3.7/site-packages/camelot/handlers.py", line 172, in parse
    self._save_page(self.filepath, p, tempdir)
  File ".venv/py37/lib/python3.7/site-packages/camelot/handlers.py", line 111, in _save_page
    infile = PdfFileReader(fileobj, strict=False)
  File ".venv/py37/lib/python3.7/site-packages/PyPDF2/_reader.py", line 1974, in __init__
    deprecation_with_replacement("PdfFileReader", "PdfReader", "3.0.0")
  File ".venv/py37/lib/python3.7/site-packages/PyPDF2/_utils.py", line 369, in deprecation_with_replacement
    deprecation(DEPR_MSG_HAPPENED.format(old_name, removed_in, new_name))
  File ".venv/py37/lib/python3.7/site-packages/PyPDF2/_utils.py", line 351, in deprecation
    raise DeprecationError(msg)
PyPDF2.errors.DeprecationError: PdfFileReader is deprecated and was removed in PyPDF2 3.0.0. Use PdfReader instead.
```

**Steps to reproduce the bug**

1. Create a new virtualenv
2. Install `camelot-py`:
   ```
   pip install camelot-py[base]
   ```
3. Run the following code:
    ```python
	import camelot

	# replace with a valid path on your local filesystem
	PDF_FILE_PATH = "/path/to/file.pdf"
	
	# raises an exception from PyPDF2
	camelot.read_pdf(PDF_FILE_PATH)
	```

**Expected behavior**

The code above should execute without any exceptions.

**Environment**

- OS: macOS 12.3.1
- Python version: 3.7
- Numpy version: 1.24.0
- OpenCV version: 4.6.0.66
- Ghostscript version: 0.7
- Camelot version: 0.10.1

**Comment by szeswee** [comment]
As a workaround, I've added this line in my `requirement.txt` for the time being:

```
PyPDF2~=2.0
```

**Comment by KshitizPandya** [comment]
Hey @szeswee, 

Gone with the steps, created a virtual environment through terminal, and executed the script in the IDE, as well as in colab, giving the same answer.

**Comment by saidakyuz** [comment]
Hey @szeswee I also tried on both platforms(see screenshots) like @KshitizPandya  and have the issue still.  Does it work for you? Can you explain it more in detail? 
![image](https://user-images.githubusercontent.com/29119961/209807016-bcc3bdd8-b5e6-487a-a52c-dd44ce3cb259.png)
![image](https://user-images.githubusercontent.com/29119961/209807228-46e280c6-c8a4-42e8-b1a7-2d3089c2aad2.png)

**Comment by MartinThoma** [comment]
As a side-note: `PyPDF2` should now be considered deprecated. We will continue development at [`pypdf`](https://pypi.org/project/pypdf/), see [History of pypdf](https://pypdf.readthedocs.io/en/latest/meta/history.html)

**Comment by owen800q** [comment]
We are hitting this issue now, any workaround fix?

**Comment by anakin87** [comment]
@vinayak-mehta if you want, I'm available to submit a PR to fix this issue.

**Comment by alprnyldz** [comment]
> As a workaround, I've added this line in my `requirement.txt` for the time being:
> 
> ```
> PyPDF2~=2.0
> ```

Thank you for the workaround fix

**Comment by KshitizPandya** [comment]
Hey @saidakyuz , I did a bit of work around and now my camelot is working fine. Am mentioning the steps below if you want to refer. 

1) Set anaconda env (preferably use python 3.7)
2) Install camelot  - `pip install camelot-py[base]`
3) It will itself download the pyPDF2 version 3.0.0, so you need to extensively change the version - `pip install pyPDF2 == 2.0`
4) I used pyCharm to work with my script so I set the environment from settings and then it worked fine. 

**Note**: It might sometimes create error showing ghostscript is not installed. You can explicitly install it from: https://ghostscript.com/releases/gsdnld.html 
and then set it computer's environment variable to bypass any issues and restart. 

Then the issue should be resolved. 

Hope it helps.

**Comment by MartinThoma** [comment]
@KshitizPandya Please replace `pip install pyPDF2 == 2.0` by `pip install 'PyPDF2<3.0'`

**Comment by KshitizPandya** [comment]
> @KshitizPandya Please replace `pip install pyPDF2 == 2.0` by `pip install 'PyPDF2<3.0'`

Thanks for the correction @MartinThoma

**Comment by dmitry-ra** [comment]
Another possible way is to downgrade installed version of `PyPDF2`:
```bash
pip install --upgrade PyPDF2==2.12.1
```

**Comment by RhacklefordGPT** [comment]
> @vinayak-mehta if you want, I'm available to submit a PR to fix this issue.

Im so close to getting my program finished, when i run in pycharm the code runs fine when i run the exe i get the 
""PyPDF2.errors.DeprecationError: PdfFileReader is deprecated and was removed in PyPDF2 3.0.0. Use PdfReader instead.[17036] Failed to execute script 'Werks' due to unhandled exception!""
error

the suggested workarounds arent working for me, probably because this is my first program. 
i would LOVE a fix or a workaround that i can do..
please advise!

**Comment by RhacklefordGPT** [comment]
> Another possible way is to downgrade installed version of `PyPDF2`:
> 
> ```shell
> pip install --upgrade PyPDF2==2.12.1
> ```

I tried this and also downgraded to PyPDF2.0, i get the same result, the deprecation error. I'm sure I'm missing something dumb. 
i am running the camelot-py[cv] version of camelot, would that have anything to do with it?

**Comment by MartinThoma** [comment]
@RhacklefordGPT most likely you downgraded it in the wrong environment. So you have two places where PyPDF2 is installed. You need to ensure to downgrade it in the correct one.

To verify, you can add the following before you import camelot:

```
import PyPDF2

print("PyPDF2==" + PyPDF2.__version__)
```

**Comment by RhacklefordGPT** [comment]
> @RhacklefordGPT most likely you downgraded it in the wrong environment. So you have two places where PyPDF2 is installed. You need to ensure to downgrade it in the correct one.
> 
> For example, you might need `pip3`. Or you might need to load a virtual environment.
> 
> To verify, you can add the following before you import camelot:
> 
> ```
> import PyPDF2
> 
> print("PyPDF2==" + PyPDF2.__version__)
> ```

Looks like that did the trick. 
my project is in a venv and I had been using the pycharm terminal to pip anything,
looks like before I was using venv I had installed it using CMD directly.
I'm still not clear on why if I use pyinstaller through Pycharm it tries to use things installed using cmd, I would think those are separated somehow, but really I do have a loose grasp of how this all works, could you recommend some further reading so I can avoid this? should I delete every installation of everything outside my venv?

**Comment by au3m** [comment]
> import PyPDF2
> 
> print("PyPDF2==" + PyPDF2.__version__)

i have already do that but i get other error 
OSError: Ghostscript is not installed. You can install it using the instructions here: https://camelot-py.readthedocs.io/en/master/user/install-deps.html
although it is installed already

**Comment by KshitizPandya** [comment]
> > import PyPDF2
> > print("PyPDF2==" + PyPDF2.**version**)
> 
> i have already do that but i get other error OSError: Ghostscript is not installed. You can install it using the instructions here: https://camelot-py.readthedocs.io/en/master/user/install-deps.html although it is installed already

Hey @au3m, 
Doing just the installation sometimes might not help. Sometimes you might need to set something in the computer's environment variables to access it easily. 
So try setting "ghostscript" to your environment variables. 

STEPS: 
1. copy the path where you have installed ghostscript. 
2. If you are using windows - search for "Edit the system environment variable" .
![image](https://user-images.githubusercontent.com/110394695/210123572-54f6cb7a-22fe-4ae8-b3f6-b59444359d55.png)

3. above dialog should open. Click on the "environment variable" tab.
4. Under "system variables" section double click "path". 
![image](https://user-images.githubusercontent.com/110394695/210123646-4b7adec2-c267-4fe9-ad78-195e0731cbea.png)

5. Click on the open space and paste the copied path of the ghostscript. 
![image](https://user-images.githubusercontent.com/110394695/210123665-6c034085-929d-4bf7-a3de-78cc9aa6952a.png)

6. Click OK and for precautions restart your device. 

After this your program should run fine without giving the ghostscript related error.

**Comment by au3m** [comment]
> > > import PyPDF2
> > > print("PyPDF2==" + PyPDF2.**version**)
> > 
> > i have already do that but i get other error OSError: Ghostscript is not installed. You can install it using the instructions here: https://camelot-py.readthedocs.io/en/master/user/install-deps.html although it is installed already
> 
> Hey @au3m, 
> Doing just the installation sometimes might not help. Sometimes you might need to set the things in the computer's environment variables to access it easily. 
> So try setting "ghostscript" to your environment variables. 
> 
> STEPS FOR REFERENCE:  
> 1. copy the path where you have installed ghostscript. 
> 2. If you are using windows - search for "Edit the system environment variable" .
> ![image](https://user-images.githubusercontent.com/110394695/210123572-54f6cb7a-22fe-4ae8-b3f6-b59444359d55.png)
> 
> 3. above dialog should open. Click on the "environment variable" tab.
> 4. Under "system variables" section double click "path". 
> ![image](https://user-images.githubusercontent.com/110394695/210123646-4b7adec2-c267-4fe9-ad78-195e0731cbea.png)
> 
> 5. Click on the open space and paste the copied path of the ghostscript. 
> ![image](https://user-images.githubusercontent.com/110394695/210123665-6c034085-929d-4bf7-a3de-78cc9aa6952a.png)
> 
> 6. Click OK and for precautions restart your device. 
> 
> After this your program should run fine without giving the ghostscript related error. 

@KshitizPandya  
Thanks bro it works now ☺️

**Comment by AChnki** [comment]
I think the problem is based on a missed migration considering the naming adjustments within PyPDF2/pypdf - see the following doc: [https://pypdf2.readthedocs.io/en/stable/user/migration-1-to-2.html](https://pypdf2.readthedocs.io/en/stable/user/migration-1-to-2.html)

Following the [The Deprecation Process](https://pypdf2.readthedocs.io/en/stable/dev/deprecations.html) of PyPDF2/pypdf they are not longer tolerated.

I adjusted the names in the handlers.py-file manually and the cli is working again. I will try to open an PR.

**Comment by kfunes3706** [comment]
hey, I am getting this error on m2 mbp, would anyone know how to fix? I've verified gs is installed
<img width="1080" alt="Screenshot 2023-01-07 at 11 22 12 PM" src="https://user-images.githubusercontent.com/112385808/211180363-6ce9f49c-709e-4c31-9786-9761b97ec2ae.png">

**Comment by Prathamesh-gunjal** [comment]
![image](https://user-images.githubusercontent.com/126472088/223682449-bc02f22e-91f2-4228-87a1-0171a2d42bdf.png)
![image](https://user-images.githubusercontent.com/126472088/223682604-9f0f80f9-ae79-46e5-8e67-7273380890df.png)
 
GETTING THIS ERROR PLEASE HELP!!

**Comment by Prathamesh-gunjal** [comment]
![image](https://user-images.githubusercontent.com/126472088/223682974-518eea33-8ee3-4c25-b507-333135669979.png)

Still getting this error please help!!

**Comment by AayushSameerShah** [comment]
If anyone trying to do this **on colab** then run the following steps:
```sh
!pip install ghostscript
!pip install camelot-py[cv]
!pip install excalibur-py
!apt install ghostscript python3-tk
```
And after that:
```python
from ctypes.util import find_library

# It will display `libgs.so.9` if installed or will print `None` if not
print(find_library("gs")) 
```

If still doesn't work:
```sh
!excalibur initdb
```
___
Source: [here](https://www.reddit.com/r/GoogleColab/comments/k7lwfc/runtimeerror_please_make_sure_that_ghostscript_is/)

**Comment by Gio-2020** [comment]
> > > import PyPDF2
> > > print("PyPDF2==" + PyPDF2.**version**)
> > 
> > 
> > i have already do that but i get other error OSError: Ghostscript is not installed. You can install it using the instructions here: https://camelot-py.readthedocs.io/en/master/user/install-deps.html although it is installed already
> 
> Hey @au3m, Doing just the installation sometimes might not help. Sometimes you might need to set the things in the computer's environment variables to access it easily. So try setting "ghostscript" to your environment variables.
> 
> STEPS FOR REFERENCE:
> 
> 1. copy the path where you have installed ghostscript.
> 2. If you are using windows - search for "Edit the system environment variable" .
>    ![image](https://user-images.githubusercontent.com/110394695/210123572-54f6cb7a-22fe-4ae8-b3f6-b59444359d55.png)
> 3. above dialog should open. Click on the "environment variable" tab.
> 4. Under "system variables" section double click "path".
>    ![image](https://user-images.githubusercontent.com/110394695/210123646-4b7adec2-c267-4fe9-ad78-195e0731cbea.png)
> 5. Click on the open space and paste the copied path of the ghostscript.
>    ![image](https://user-images.githubusercontent.com/110394695/210123665-6c034085-929d-4bf7-a3de-78cc9aa6952a.png)
> 6. Click OK and for precautions restart your device.
> 
> After this your program should run fine without giving the ghostscript related error.

Thanks! Help me a lot.

**Comment by jmartle** [comment]
pip install --upgrade PyPDF2==2.12.1

works

**Comment by juliatong** [comment]
> Hey @saidakyuz , I did a bit of work around and now my camelot is working fine. Am mentioning the steps below if you want to refer.
> 
> 1. Set anaconda env (preferably use python 3.7)
> 2. Install camelot  -
>    `pip install camelot-py[base]`
> 3. It will itself download the pyPDF2 version 3.0.0, so you need to extensively change the version -
>    `pip install 'PyPDF2<3.0'`
> 4. I used pyCharm to work with my script so I set the environment from settings and then it worked fine.
>    ![image](https://user-images.githubusercontent.com/110394695/209962792-78e0e6ce-4d21-4666-b617-fac7a3d8b8bc.png)
> 
> Environment packages: camelot-py 0.10.1 ghostscript 0.7 pypdf2 2.0.0
> 
> **Note**: It might sometimes create error showing ghostscript is not installed. You can explicitly install it from: https://ghostscript.com/releases/gsdnld.html and then set it computer's environment variable to bypass any issues and restart.
> 
> Then the issue should be resolved.
> 
> OUTPUT: ![image](https://user-images.githubusercontent.com/110394695/209962697-f31e9af6-bfed-46ed-9308-5b56cda2ea26.png)
> 
> Hope it helps.

I set all the libs exact same version as yours, yet error remains...
Environment packages: camelot-py 0.10.1 ghostscript 0.7 pypdf2 2.0.0

**Comment by Rommel2323** [comment]
In my case python -m pip install --upgrade PyPDF2==2.12.1 has worked. It uninstalled PyPDF2 and installed PyPDF2.12.1 and now it successfully extracting table from pdf doc. Thanks for the support.

**Comment by yousseftarhri** [comment]
In my case i did **pip install 'PyPDF2<3.0'**
it works.
