### ISSUE TITLE
TableList error in Camelot and in Excalibur

### ISSUE THREAD

**Issue by njss** [camelot-dev/camelot#37]
Occurs when running the camelot example (or when uploading a pdf in excalibur):

Traceback (most recent call last):
  File "camelottest.py", line 1, in <module>
    import camelot
  File "C:\Program Files\Python37\lib\site-packages\camelot\__init__.py", line 6, in <module>
    from .io import read_pdf
  File "C:\Program Files\Python37\lib\site-packages\camelot\io.py", line 5, in <module>
    from .handlers import PDFHandler
  File "C:\Program Files\Python37\lib\site-packages\camelot\handlers.py", line 8, in <module>
    from .core import TableList
ImportError: cannot import name 'TableList' from 'camelot.core' (C:\Program Files\Python37\lib\site-packages\camelot\core\__init__.py)

**Comment by jndz2** [comment]
The same problem occurs on my ubuntu machine.

`/usr/local/lib/python3.6/dist-packages/camelot/__init__.py in <module>()
      4 
      5 from .__version__ import __version__
----> 6 from .io import read_pdf
      7 from .plotting import PlotMethods
      8 

/usr/local/lib/python3.6/dist-packages/camelot/io.py in <module>()
      3 import warnings
      4 
----> 5 from .handlers import PDFHandler
      6 from .utils import validate_input, remove_extra
      7 

/usr/local/lib/python3.6/dist-packages/camelot/handlers.py in <module>()
      6 from PyPDF2 import PdfFileReader, PdfFileWriter
      7 
----> 8 from .core import TableList
      9 from .parsers import Stream, Lattice
     10 from .utils import (

ImportError: cannot import name 'TableList'`

**Comment by jndz2** [comment]
pip install camelot-py[cv] has fixed the problem.

**Comment by naveenpundir99** [comment]
nothing hapend still same

**Comment by naveenpundir99** [comment]
ImportError                               Traceback (most recent call last)
<ipython-input-1-679d8f55abf0> in <module>
----> 1 import camelot

~\AppData\Roaming\Python\Python37\site-packages\camelot\__init__.py in <module>
      4 
      5 from .__version__ import __version__
----> 6 from .io import read_pdf
      7 from .plotting import PlotMethods
      8 

~\AppData\Roaming\Python\Python37\site-packages\camelot\io.py in <module>
      3 import warnings
      4 
----> 5 from .handlers import PDFHandler
      6 from .utils import validate_input, remove_extra
      7 

~\AppData\Roaming\Python\Python37\site-packages\camelot\handlers.py in <module>
      6 from PyPDF2 import PdfFileReader, PdfFileWriter
      7 
----> 8 from .core import TableList
      9 from .parsers import Stream, Lattice
     10 from .utils import (

ImportError: cannot import name 'TableList' from 'camelot.core' (C:\Users\Admin\AppData\Roaming\Python\Python37\site-packages\camelot\core\__init__.py)

**Comment by Peins** [comment]
Me too
