### ISSUE TITLE
<BugReport>

### ISSUE THREAD

**Issue by majiayu000** [camelot-dev/camelot#394]
**Describe the bug**

Hi, it seems something not updated for the instruction:

`pip install "camelot-py[base]" `

The newest version is 0.11.0, but I got 0.9.0 when using this command.

![image](https://github.com/camelot-dev/camelot/assets/19658300/f02ecbb7-458d-4200-ae2f-e5aa78bcb64f)

Here is my versions:
![image](https://github.com/camelot-dev/camelot/assets/19658300/2390364e-58e5-4891-8989-e001fd4945a3)

**Environment**

- OS: [e.g. macOS] macOS-13.4-arm64-arm-64bit
- Python version: 3.11.2
- Numpy version: 1.25.2
- OpenCV version: 4.8.0
- Ghostscript version: 4.8.0
- Camelot version: 0.9.0

**Additional context**

**Comment by foarsitter** [comment]
We are experience some difficulties with getting a new release out of the door. The issue your are running into is already solved. The only solution at this moment is to install https://pypi.org/project/camelot-fork or install the master branch with pip: `pip install git+https://github.com/camelot-dev/camelot.git`
