### ISSUE TITLE
Assuming whole page as one table in stream flavour

### ISSUE THREAD

**Issue by spidysenses** [camelot-dev/camelot#43]
Camelot is assuming whole page as one table even there is sufficient space before and after table.
Only setting I could find is **column_tol**  which is default at Zero. It doesn't make any difference. 
Is there any other setting for this?
And please answer one more question.
How are your coordinates different from pdfplumber?

[pdf](https://www.icra.in/Rationale/ShowRationaleReport/?Id=70577)

**Comment by vinayak-mehta** [comment]
Since the table exists only on a very small part of the page, it's not able to contribute to the guessed table. You can try using the `table_area` keyword argument.

I haven't been able to get time to look into how `pdfplumber` coordinates are different.
