### ISSUE TITLE
two bug!

### ISSUE THREAD

**Issue by zoheirdibaj** [camelot-dev/camelot#456]
**Describe the bug**

module 'camelot' has no attribute 'read_pdf' (1)
cannot import name 'TableList' from 'camelot.core'(2)
when i install camelot-py, i get erorr number (1)
when i uninstall camelot-py and i just have camelot i get erorr number(2)
i uninstall every version and i installed camelot[all]
but i still getting erorr number (1)
**Code**

```
import camelot
tables = camelot.read_pdf('budget1402_archive.pdf')



print(tables)

```

**PDF**

**Screenshots**

**Environment**

- OS: [e.g. macOS]
- Python version:
- Numpy version:
- OpenCV version:
- Ghostscript version:
- Camelot version:

**Additional context**

**Comment by zhangnn520** [comment]
pip install "camelot-py[base]"

**Comment by bosd** [comment]
Thanks for mentioning this issue. This has been fixed, checkout out the latest release.
