### ISSUE TITLE
Conversion to csv for Hindi pdf is not correct

### ISSUE THREAD

**Issue by raghuramdr** [camelot-dev/camelot#53]
I am using Camelot to convert [this](https://drive.google.com/file/d/1QrnXdTGk8n8TsohKRQ5u7guZKezJgcMt/view?usp=sharing) document to csv. The csv [file](https://drive.google.com/file/d/1kLinDfoek0n_RcVAMD1nrxuDebOh2BQk/view?usp=sharing) is created however, the issue is it is not correct. 

As can be seen from the shared original file and the converted csv file, the Hindi characters are not converted properly. 

```
import camelot
tables = camelot.read_pdf('Demand_ Estimate.pdf', flavor='stream')
tables[0].to_csv('demand_estimate.csv')
```

This is my code.

**Comment by iambatman07** [comment]
Hey @vinayak-mehta , camelot uses "pdfminer" underneath for text recognition, so my guess is it's a bug from their end and to be honest character recogntion for any native languages is not so good to begin with so I suggest you explore the Amazon Textract for this it's proven to have good results.

**Comment by vinayak-mehta** [comment]
@raghuramdr Looks like a problem with the PDF itself. You can see that by copy pasting the hindi text.
