### ISSUE TITLE
why  module 'camelot' has no attribute 'read_pdf'

### ISSUE THREAD

**Issue by 13256701918** [camelot-dev/camelot#54]
"""""""""""""""""""
import camelot

tables=camelot.read_pdf("foo.pdf")
tables[0].df
tables.export("foo.csv",f="csv",comress=True)
tables[0].to_csv("foo.csv")

"""""""""""""""""
why ?

  File "C:/Users/jiuyang.wei/Desktop/ocr/another/camelot.py", line 8, in <module>
    import camelot

  File "C:\Users\jiuyang.wei\Desktop\ocr\another\camelot.py", line 10, in <module>
    tables=camelot.read_pdf("foo.pdf")

AttributeError: module 'camelot' has no attribute 'read_pdf'

why  module 'camelot' has no attribute 'read_pdf'

**Comment by UgyenNorbu** [comment]
I have this error in my code. I could not get a solution online. Please help.
