### ISSUE TITLE
Update pypi page for camelot

### ISSUE THREAD

**Issue by dimitern** [camelot-dev/camelot#6]
@vinayak-mehta Now that the main repo has changed to this one, the https://pypi.org/project/camelot-py/ page should be also updated.

**Comment by vinayak-mehta** [comment]
Yes, we can do that with the next release. There's already some fixes on master. I'll see if I can put more fixes in, will update the [Roadmap](https://github.com/camelot-dev/camelot/wiki/Roadmap). Planning on releasing `0.7.3` this weekend.

**Comment by vinayak-mehta** [comment]
This was fixed.
