### ISSUE TITLE
Add opencollective link to documentation and README

### ISSUE THREAD

**Issue by vinayak-mehta** [camelot-dev/camelot#62]

**Comment by pravarag** [comment]
@vinayak-mehta I would like to work on this issue.

**Comment by vinayak-mehta** [comment]
Thanks! This is the link: https://opencollective.com/camelot

**Comment by vinayak-mehta** [comment]
@pravarag You can take ideas from how we've set up the URL and supporting text from Excalibur.

**Comment by pravarag** [comment]
@vinayak-mehta Following PR has been created to fix this issue: https://github.com/camelot-dev/camelot/pull/65

**Comment by vinayak-mehta** [comment]
Closed in #65.
