### ISSUE TITLE
Link to python-tk package shows error.

### ISSUE THREAD

**Issue by sidntrivedi012** [camelot-dev/camelot#64]
The link to the `tk` package in the README shows error. We need to replace it with this link : https://packages.ubuntu.com/bionic/python/python-tk

/cc: @vinayak-mehta

**Comment by pravarag** [comment]
@sidntrivedi012 are you working on this issue? Otherwise I would like to take it.

**Comment by sidntrivedi012** [comment]
@pravarag , You can take it. I'm not working on it as of now.

**Comment by pravarag** [comment]
@vinayak-mehta following PR has been created: https://github.com/camelot-dev/camelot/pull/86

**Comment by sidntrivedi012** [comment]
Solved in #86. Thanks.
