### ISSUE TITLE
Few columns are missing while to extracting data from the table

### ISSUE THREAD

**Issue by vinayak-mehta** [camelot-dev/camelot#74]
Refer https://github.com/atlanhq/camelot/issues/324.

**Comment by pravarag** [comment]
I reproduced the issue of mentioned PDF files in the referenced link for, the particular portion of table in PDF 1 & 2 comparing with PDF 3. Table area used were['12, 427, 829, 374'] and I was able to see all the columns for the dataframe in that particular area.

**Comment by vinayak-mehta** [comment]
@Jackblackpearl You can try using table areas like mentioned in the comment above.

**Comment by Jackblackpearl** [comment]
Thank vinayak. Will try waiting for long time for your inputs
