### ISSUE TITLE
read_pdf fails with an index out of range

### ISSUE THREAD

**Issue by vinayak-mehta** [camelot-dev/camelot#75]
Refer https://github.com/atlanhq/camelot/issues/306.

**Comment by pravarag** [comment]
@vinayak-mehta I would like to work on this issue.

**Comment by rohang1997** [comment]
hey,

go to /lib/python3.6/site-packages/pdfminer/cmapdb.py

at line around 399,
instead of 
self.cmap.add_cid2unichr(s1+i, code[i])

put this,
try:
    self.cmap.add_cid2unichr(s1+i, code[i])
except:
     pass

problem solved! 

one more problem is , it is not able to detect more than one table

**Comment by vinayak-mehta** [comment]
This will probably have to be fixed in pdfminer.
