### ISSUE TITLE
Getting ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by pravesh29** [camelot-dev/camelot#77]
Hi, I am getting this particular error in this specific pdf only and all other pdf have been extracted easily. Kindly look into this. I have send the screenshot of error and pdf too.
[AC172.pdf](https://github.com/camelot-dev/camelot/files/3723453/AC172.pdf)
![Screenshot from 2019-10-14 13-18-10](https://user-images.githubusercontent.com/28472207/66735963-84590b80-ee85-11e9-8efb-c8467653dfd3.png)

**Comment by rohang1997** [comment]
hey, 

actually your pdf have some unknown characters at the end of file. 
what you can do is 

go to https://pdfjoiner.com/

and just start the process and redownload the file .
It should remove the unknown characters. 

PyPDF2 library is not finding the end of file and therefore the error. 
Please redownload the new file created by pdfjoiner and try
