### ISSUE TITLE
PdfReadWarning: Multiple definitions in dictionary at byte 0x29f for key /Type [generic.py:588]

### ISSUE THREAD

**Issue by pravesh29** [camelot-dev/camelot#84]
getting this issue again and again for multiple pdf.
![Screenshot from 2019-10-15 10-54-22](https://user-images.githubusercontent.com/28472207/66802523-5681ce80-ef3a-11e9-8f37-7c825baaa3fb.png)

**Comment by vinayak-mehta** [comment]
Not enough information to reproduce.
