### ISSUE TITLE
table_regions property doesn't work with 'stream'

### ISSUE THREAD

**Issue by brockerdock** [camelot-dev/camelot#93]
Hello,

I'm trying to detect a table without lines within a pdf-page. As the table is without lines I need to use the Stream-method. Sadly Stream only recognizes a table on the upper part of the page. I therefor thought it would come handy to specify the area on the page where the table lies. Doing so with the table_regions option does work for lattice but not for stream.

Here the output of the table_regions option with using the lattice-method:
`a=camelot.read_pdf('table_region.pdf',` flavor='lattice', table_regions=['48,565,570,187'])
`camelot.plot(a[0],` kind='contour')
![Lattice](https://user-images.githubusercontent.com/56741718/67127031-c58c4b00-f1f8-11e9-9f4f-ac13c1af985f.PNG)

However if I use the stream-method:
`a=camelot.read_pdf('table_region.pdf',` flavor='stream', table_regions=['48,565,570,187'])

I get the error:

> Traceback (most recent call last):

>  File "<ipython-input-198-95682fd0b33f>", line 1, in <module>
>     a=camelot.read_pdf('table_region.pdf', flavor='stream', table_regions=['48,565,570,187'])

>   File "C:\Users\mlaptop\Anaconda3\lib\site-packages\camelot\io.py", line 106, in read_pdf
>     layout_kwargs=layout_kwargs, **kwargs)

>   File "C:\Users\mlaptop\Anaconda3\lib\site-packages\camelot\handlers.py", line 162, in parse
>     layout_kwargs=layout_kwargs)

>   File "C:\Users\mlaptop\Anaconda3\lib\site-packages\camelot\parsers\stream.py", line 419, in extract_tables
>  self._generate_table_bbox()

>  File "C:\Users\mlaptop\Anaconda3\lib\site-packages\camelot\parsers\stream.py", line 289, in >_generate_table_bbox
>    x1, y1, x2, y2 = region

>ValueError: too many values to unpack (expected 4)

**Comment by brockerdock** [comment]
I managed to get the stream-method to work with the table_regions-property by changing some code in the file "C:\Users\mlaptop\Anaconda3\lib\site-packages\camelot\parsers\stream.py":

` for region in self.table_regions:
          x1, y1, x2, y2 = region`

to
`for region in self.table_regions:
    x1, y1, x2, y2 = region.split(",")
    x1=float(x1)
    y1=float(y1)
    x2=float(x2)
    y2=float(y2)`

**Comment by vinayak-mehta** [comment]
@brockerdock This was fixed on master (https://github.com/camelot-dev/camelot/blob/master/camelot/parsers/stream.py#L300). Need to make a release.
