### ISSUE TITLE
Tables without borders are not identified as tables

### ISSUE THREAD

**Issue by ashokbalaraman** [camelot-dev/camelot#95]
If there are tables without the side bars, the camelot.read_pdf(filename) returns <TableList n=0>

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4254480/pdf/e2014.00187.pdf

**Comment by anakin87** [comment]
What is your output?
Did you try flavor=stream?

**Comment by ashokbalaraman** [comment]
I tried.  With that it is returning all the text in the PDF documents as tables. No luck.

**Comment by anakin87** [comment]
You can specifiy [table areas](https://camelot-py.readthedocs.io/en/master/user/advanced.html#specify-table-areas).
You can detect table coordinates doing [visual debugging](https://camelot-py.readthedocs.io/en/master/user/advanced.html#visual-debugging).

**Comment by vinayak-mehta** [comment]
@ashokbalaraman Please try the above options and reopen if you still face any issues.
